/** kebab-case module id → camelCase import binding (knowledge-base → knowledgeBase). */
export const camelId = (id: string): string => id.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

/**
 * Emit content/shell/src/modules/index.ts for the selected modules — the same
 * strict convention the checked-in registry follows (fixed export name
 * `moduleDescriptor` per module dir).
 */
export function generateModuleRegistry(selectedIds: string[]): string {
  const imports = selectedIds.map((id) => `import { moduleDescriptor as ${camelId(id)} } from './${id}';`).join('\n');
  const list = selectedIds.map(camelId).join(', ');
  return `// @chatfuel:module-registry — generated by the Chatfuel wizard (selected modules).
import type { ModuleDescriptor } from './types';
${imports}

export const MODULES: ModuleDescriptor[] = [${list}];
`;
}
