import { camelId } from './moduleRegistry';

/**
 * Emit the app's `operationDocs.ts` — the barrel of generated GraphQL
 * namespaces the proxy builds its operation registry from.
 *
 * Namespace imports and not `export *`: two modules export the same fragment
 * name (`FileInfoFragmentDoc` lives in both contacts and livechat), and a
 * star-reexport of both makes such a name ambiguous — dropped from the barrel
 * silently, with no error from tsc and none at runtime. A namespace keeps every
 * module's exports behind its own name, so nothing can collide and nothing can
 * go missing; the proxy walks the values and takes the ones that carry an
 * operation.
 *
 * The path is the same relative shape in both layouts the wizard writes:
 * `src/operationDocs.ts` beside `src/vendor/api` in a scaffolded app, and
 * `src/chatfuel/operationDocs.ts` beside `src/chatfuel/vendor/api` in an
 * embedded one. `.js` because the Vercel function's builder transpiles rather
 * than bundles and leaves specifiers as written — the same reason the proxy's
 * own imports carry it.
 */
export function generateOperationDocs(generatedIds: readonly string[]): string {
  const imports = generatedIds
    .map((id) => `import * as ${camelId(id)} from './vendor/api/generated/${id}/graphql.js';`)
    .join('\n');
  const list = generatedIds.map(camelId).join(', ');
  return `// @chatfuel:operation-docs — generated by the Chatfuel wizard (selected modules).
// The proxy refuses an operation that is not in here, so this file is the
// app's own surface: regenerate it when the module set changes.
${imports}

export const operations = [${list}];
`;
}
