#!/usr/bin/env node
// ---------------------------------------------------------------------------
// The operation allowlist the proxy enforces, derived from what the app sends
// ---------------------------------------------------------------------------
// The account schema is far wider than any one app. This one uses 348 fields, and
// every one is written down: content/modules/<id>/skill/examples/operations.graphql
// is the codegen input, so a document the app can send is a document that is in
// one of those files. Everything else in the schema is reachable through the
// proxy today for no reason but that nobody enumerated it — and reachable under
// the master token, which is the whole account.
//
// So the list is derived rather than curated: the root fields of every shipped
// operation, following a spread into its fragment because `mutation { ...f }`
// is the same request written differently. It is a NAME list and not a
// signature list — the bot fence, the account denylists and the resource fence
// are what say who may name what. This one only says which questions exist.
//
// Generated into content/vite-plugin-proxy/src/allowedOperations.ts, which is
// vendored into scaffolded apps with the rest of the proxy. Run this file to
// rewrite it; pass 17 re-derives and fails when the two disagree.
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Kind, parse, type FragmentDefinitionNode, type SelectionSetNode } from 'graphql';

const HERE = dirname(fileURLToPath(import.meta.url));
export const ALLOWED_OPERATIONS_FILE = join(HERE, '..', 'content', 'vite-plugin-proxy', 'src', 'allowedOperations.ts');

/**
 * The root fields of every operation in every module's operations.graphql.
 *
 * A fragment spread at the root is followed, an inline fragment is descended
 * into, and an alias is ignored — it renames the answer, never the field. This
 * mirrors `rootFields` in the proxy's queryAnalysis.ts, which is what reads a
 * document at request time; the two must agree, or the list would be derived
 * from one reading and enforced against another.
 */
export function deriveAllowedOperations(modulesDir: string): string[] {
  const roots = new Set<string>();
  for (const id of readdirSync(modulesDir).sort()) {
    const file = join(modulesDir, id, 'skill', 'examples', 'operations.graphql');
    if (!existsSync(file)) continue;
    const doc = parse(readFileSync(file, 'utf8'), { noLocation: true });
    const fragments = new Map<string, FragmentDefinitionNode>();
    for (const def of doc.definitions) {
      if (def.kind === Kind.FRAGMENT_DEFINITION) fragments.set(def.name.value, def);
    }
    const walk = (set: SelectionSetNode, seen: Set<string>): void => {
      for (const selection of set.selections) {
        if (selection.kind === Kind.FIELD) {
          roots.add(selection.name.value);
        } else if (selection.kind === Kind.INLINE_FRAGMENT) {
          walk(selection.selectionSet, seen);
        } else {
          const name = selection.name.value;
          if (seen.has(name)) continue;
          seen.add(name);
          const fragment = fragments.get(name);
          if (fragment) walk(fragment.selectionSet, seen);
        }
      }
    };
    for (const def of doc.definitions) {
      if (def.kind === Kind.OPERATION_DEFINITION) walk(def.selectionSet, new Set());
    }
  }
  return [...roots].sort();
}

/** The generated module, byte for byte — prettier reads it like any other file. */
export function renderAllowedOperations(fields: readonly string[]): string {
  return `/**
 * The operations this app sends, and the only ones the proxy forwards.
 *
 * GENERATED by scripts/allowed-operations.ts from every module's
 * skill/examples/operations.graphql — the same documents codegen reads. Do not
 * edit: the repository's validator re-derives this list and fails when a hand
 * edit or a stale copy makes the two disagree.
 *
 * The fence this feeds is a name check on an operation's ROOT fields, and it is
 * the outermost of them: an operation nobody wrote is refused before any
 * question about who may name what is asked. See proxyConfig.ts for how a
 * deployment that sends more than the shipped modules do extends or turns it
 * off.
 */
export const ALLOWED_ROOT_FIELDS: ReadonlySet<string> = new Set([
${fields.map((field) => `  '${field}',`).join('\n')}
]);
`;
}

if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
  const fields = deriveAllowedOperations(join(HERE, '..', 'content', 'modules'));
  writeFileSync(ALLOWED_OPERATIONS_FILE, renderAllowedOperations(fields));
  console.log(`content/vite-plugin-proxy/src/allowedOperations.ts: ${fields.length} root fields`);
}
